[package]
name = "bitcoin_service"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
bitcoin-rpc = "0.2.0"
dotenv = "0.15"
